### ISSUE TITLE
For help '../MAVControlWithSNN/Builds/MAVControlWithSNN.exe'

### ISSUE THREAD

**Issue by kimsolo** [JeremieGince/MAVControlWithSNN#2]
Hello, the error: '../MAVControlWithSNN/Builds/MAVControlWithSNN.exe', have you seen before? What should I do to solve it?

**Comment by JeremieGince** [comment]
Hi!

Can I have more details on the error please? Now the only thing I see is a path the executable file. But my guess is that you didn't build the unity project and getting a FileNotFoundError, is that it?

Thank you for your interest in my work!

**Comment by JeremieGince** [comment]
> Hello, the error: '../MAVControlWithSNN/Builds/MAVControlWithSNN.exe', have you seen before? What should I do to solve it?

Hi!

Can I have more details on the error please? Now the only thing I see is a path the executable file. But my guess is that you didn't build the unity project and getting a FileNotFoundError, is that it?

Thank you for your interest in my work!

**Comment by kimsolo** [comment]
Hi！
Thanks for your reply! Actualy, I have been installing the enviornment these days. Because I have not used Unity3d before, my progress is a little slow. Now I face some problems, if you don't mind, I hope I can list some errors compiled in unity project to ask your help T^T.

The compile situation errors are as follow:
I used 'ML Agents Version 2.1.0-exp.1', 'Standard Assets', 'Unity Version.2020.3.30f1c1', and 'OpenCV plus Unity' in the pacakage manager. But there are some errors in the compile console like:

1、Prefab instance problem: Wall (Missing Prefab with guid: c6790489629e8e743a5fd745045bbadc)
2、Prefab instance problem: Wall (Missing Prefab with guid: c6790489629e8e743a5fd745045bbadc). 4 instances are missing the same Prefab
3、Prefab instance problem: Missing Prefab with guid: 8b826a7c5dffaf04d99fa3f39f8d9060
4、Problem detected while opening the Scene file: 'Assets/Drones/_Drone_DemoScene.unity'.
......
And some similar errors as above.
I'm a little inexperienced in the unity field, maybe i have made some stupid mistakes. Could you do me a favor of solving the compile errors, thanks a million!

I am very interesed in your work!

**Comment by JeremieGince** [comment]
Sorry for the late answer. You can install the Free Wooden pack here 

https://assetstore.unity.com/packages/2d/textures-materials/floors/free-pack-woden-planks-214610 

or you can just use other materials. The point of the materials was juste to give some texture in the environment so the camera and the neural network will have something to work with.

**Comment by kimsolo** [comment]
Hi，today I try to modify the guid of ‘.meta’ files, like 'DivergenceCamera.prefab.meta', 'Rotor.prefab.meta'， because I find that the guid used in prefab is unmatched to the metas Generated.
Whether should I modify the guids of meta follow your calling sequence？
I am a beginner in unity3d, sorry~

**Comment by JeremieGince** [comment]
To be able to help you more, I clone the repo on another computer and here's the steps that I did to make the project works:

1. clone the repo
2. open the project so the root of the unity project is MAVControlWithSNN/MAVControlWithSNN
3. install the unity editor version 2020.3.30f1 from unity3d.com/get-unity/download/archive
4. open the project with unity hub
5. install the MLAgents package version 2.1.0-exp.1 from the package manager
6. Open and play the scene LandingAcademy.

During the first attempt to clone the repo, I realized that I didn't commit my *.*.meta files and it the cause of almost all this trouble. After adding them to the repo, I redo all the previous steps and it seems to work. You should therefore re-clone the repo and start a fresh project to make sure everything is in order.

I'm sorry for this error on my part and I hope this will fix your problems.

**Comment by kimsolo** [comment]
Thanks for your help so much. The unity environment goes well, and I am studying your codes carefully.

**Comment by JeremieGince** [comment]
Since the problem seems to be solved, I will close the current issue. For the code, note that it is currently under development and there might be a big update in the next few weeks. Indeed, I am currently working on a new package called NeuroTorch where I have improved my dynamics and training loops. I will soon use this new package to try to control the MAV. Stay tuned and thanks again for your interest.
